## Report FIO results for EBS Benchmark on gp2 and gp3

Scenario (clusters):
- t1: OCP cluster with 1x gp2
- t2: OCP cluster with 2x gp2 (etcd isolated)
- t3: OCP cluster with 1x gp3
- t4: OCP cluster with 2x gp3 (etcd isolated)

This report aggregates the data collected on "battery 2" (named `b2`), that tested all control plane disks on layouts described above.

The script to create the "battery 2" and collect the data is defined (by WIP script) [here](https://github.com/mtulio/openshift-cluster-benchmark-lab/blob/init/run-test.sh#L250-L271)

References:
 - [FIO doc](https://fio.readthedocs.io/en/latest/fio_doc.html)
 - This report (notebook): reports/fio-ebs_gp3-b2.ipynb
 - This report (markdown/exported): docs/examples/fio-ebs_gp3-b2.md

In [1]:
# install dependencies
! pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (1.3.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.8/site-packages (from pandas) (1.21.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
import os
import json
import pandas as pd
from IPython.display import display

In [3]:
results_path=(f"/results")

results_fio = {}

# files is saved on the format: {battery_id}_{cluster_id}-fio-{hostname}.tar.gz
filter_results_by_battery="b2_"

In [4]:
results_path

'/results'

In [5]:
results_dirs = []
for res in os.listdir(results_path):
    if not res.startswith(filter_results_by_battery):
        continue
    # expects that files was extracted. TODO: extract it
    if res.endswith(".tar.gz"):
        continue
    results_dirs.append(res)

In [6]:
results_dirs

['b2_t1-fio-ip-10-0-137-218.ec2.internal',
 'b2_t2-fio-ip-10-0-142-88.ec2.internal',
 'b2_t3-fio-ip-10-0-137-24.ec2.internal',
 'b2_t4-fio-ip-10-0-133-152.ec2.internal']

In [7]:
def build_node_result(battery_id, test_name, node_id):
    global results_fio
    try:
        x = results_fio[f"{battery_id}"]
    except KeyError:
        results_fio[f"{battery_id}"] = []
        pass
   
    return

In [8]:
def discovery_and_load_fio_results(fpath, battery_id):
    """
    Walk through fio result dir and load JSON files with FIO results,
    returning only desired metrics for each test.
    """
    global results_fio
    for root, dirs, files in os.walk(fpath):
        for file in files:
            if file.endswith(".json"):
                fpath=os.path.join(root, file)
                with open(fpath, 'r') as f:
                    jdata=json.loads(f.read())

                    # Extract jobId from different standards (latest is fio_io_)
                    try:
                        jobId = jdata['jobs'][0]['jobname'].split('etcd')[1]
                    except Exception as e:
                        jobId = jdata['jobs'][0]['jobname'].split('fio_io_')[1]
                        pass

                    # Collect only desired data from entire FIO payload, for each test.
                    # battery_id is: batteryName+clusterName
                    # Considering only one job by result.
                    results_fio[f"{battery_id}"].append({
                        "node_name": f"{node_id}",
                        "jobname": jdata['jobs'][0]['jobname'],
                        "jobID": jobId,
                        "sync_lat_max_ms": (float(jdata['jobs'][0]['sync']['lat_ns']['max'])/1e+6),
                        "sync_lat_mean_ms": (float(jdata['jobs'][0]['sync']['lat_ns']['mean'])/1e+6),
                        "sync_lat_stddev_ms": (float(jdata['jobs'][0]['sync']['lat_ns']['stddev'])/1e+6),
                        "sync_lat_p99_ms": (float(jdata['jobs'][0]['sync']['lat_ns']['percentile']['99.000000'])/1e+6),
                        "sync_lat_p99.9_ms": (float(jdata['jobs'][0]['sync']['lat_ns']['percentile']['99.900000'])/1e+6)
                    })

In [9]:
def aggregate_metric(metric_name):
    """
    Filter desired {metric_name}, extract the jobs (rows) for each cluster (columns),
    and return the data frame.
    JobId | {cluster1}  | [...clusterN |]
    #id   | metricValue | [...metricValue |]
    """
    global results_fio
    data_metric = {}
    for bat in results_fio.keys():
        for res_bat in results_fio[bat]:
            try:
                jid = data_metric[res_bat['jobID']]
            except KeyError:
                data_metric[res_bat['jobID']] = {
                    "job_Id": res_bat['jobID']
                }
                jid = data_metric[res_bat['jobID']]
                pass
            jid[bat] = res_bat[metric_name]
    data_pd = []
    for dk in data_metric.keys():
        row = []
        row.append(data_metric[dk]['job_Id'])
        data_pd.append(data_metric[dk])

    return pd.read_json(json.dumps(data_pd))

In [10]:
def aggregate_by_node():
    """
    Aggregate all available metrics by node, returning a list of values for each one.
    {
        "{node_name}": [{...metrics}]
    }
    """
    global results_fio
    data_metrics = {}
    ignore_keys = ['node_name', 'jobname', 'jobID']
    for bat in results_fio.keys():
        for res_bat in results_fio[bat]:
            try:
                jid = data_metrics[res_bat['node_name']]
            except KeyError:
                data_metrics[res_bat['node_name']] = []

                pass
            metric = {
                    'battery_id': bat,
                    "job_Id": res_bat['jobID']
                }
            for rbk in res_bat.keys():
                if rbk in ignore_keys:
                    continue
                metric[rbk] = res_bat[rbk]
            data_metrics[res_bat['node_name']].append(metric)
    return data_metrics

In [11]:
def _df_style_high(val, value_yellow=None, value_red=None):
    "Data frame styling / cell formating"
    color = None
    if (value_yellow != None) and (val >=  value_yellow):
        color = 'yellow'
    if (value_red != None) and (val >=  value_red):
        color = 'red'
    if color == None:
        return color
    #return f"color: {color}"
    return f"background-color: {color}"

## Discovery and Load results

In [12]:
# Discovery fio payload [json] files created by battery/cluster
# Expected directory name: {batteryId}-fio-{node_name}
# All results will be saved on global var results_fio
for res in results_dirs:
    battery_id = res.split('-')[0]
    test_name = res.split('-')[1]
    node_id = res.split(f"{test_name}-")[1]

    build_node_result(battery_id, test_name, node_id)
    
    discovery_and_load_fio_results(f"{results_path}/{res}", battery_id)

## Results

As described, the tests was done in 4 clusters in two disk layouts (single disk, etcd isolated) using gp2 and gp3. The volume has same capacity using standard values for IOPS and throughput (gp3)

- Total of FIO consecutive tests: 50
- Max IOPS on all jobs job: ~1.5/2k IOPS
- Max IOPS for gp2 device: 386 (capacity=128GiB, throughput*=128 MiB/s)
- Max IOPS for gp3 device: 3000 (capacity=128GiB, throughput=120MiB/s) 

\*[Important note from AWS doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html): 
*"The throughput limit is between 128 MiB/s and 250 MiB/s, depending on the volume size. Volumes smaller than or equal to 170 GiB deliver a maximum throughput of 128 MiB/s. Volumes larger than 170 GiB but smaller than 334 GiB deliver a maximum throughput of 250 MiB/s if burst credits are available. Volumes larger than or equal to 334 GiB deliver 250 MiB/s regardless of burst credits. gp2 volumes that were created before December 3, 2018 and that have not been modified since creation might not reach full performance unless you modify the volume."*


____
____
**FIO sync lattency p99 in ms (sync_lat_p99_ms)**

Summary of results:
- after 32th job the gp2 disks consumed all burst credits (higher than max [380 IOPS]) and become slow (5/6x) due to throttlings
- the cluster with etcd as second disk using gp2 was more reliable for a longer period, comparing with single disk node
- gp3 become bellow from max and stable until the end of all tests
- gp3 in normal conditions had lattency higher than gp2
- Trade-off in reliability (when long intensive IOPS) and performance (in normal operation)

TODO:
- Collect time and Load1 between each job (it's available on runtime log)
- Compare gp2 and gp3 in perc

In [13]:
df = aggregate_metric('sync_lat_p99_ms').rename(columns={"b2_t1": "gp2x1","b2_t2": "gp2x2","b2_t3": "gp3x1","b2_t4": "gp3x2"})
df.style.applymap(_df_style_high, subset=["gp2x1", "gp2x2", "gp3x1", "gp3x2"], value_yellow=5.0, value_red=10.0)

____
**FIO sync lattency p99.9 in ms (sync_lat_p99.9_ms)**

- Total of FIO consecutive tests: 50
- Max IOPS on this job: 2k IOPS
- Max IOPS on gp2: 386 (128GiB)
- Max IOPS on gp3: 3000 [default] (128GiB) 

Summary of results:
- Same points of sync_lat_p99_ms; plus:
- isolated etcd disk reported slower than single disk
- gp3 become stable in a long period of writes

In [14]:
df = aggregate_metric('sync_lat_p99.9_ms').rename(columns={"b2_t1": "gp2x1","b2_t2": "gp2x2","b2_t3": "gp3x1","b2_t4": "gp3x2"})
df.style.applymap(_df_style_high, subset=["gp2x1", "gp2x2", "gp3x1", "gp3x2"], value_yellow=5.0, value_red=10.0)

____
**FIO sync lattency Mean in ms (sync_lat_mean_ms)**

- Total of FIO consecutive tests: 50
- Max IOPS on this job: 2k IOPS
- Max IOPS on gp2: 386 (128GiB)
- Max IOPS on gp3: 3000 [default] (128GiB) 

Summary of results:
- gp2: isolated etcd disk reported slower than single disk
- gp3: had similar results in both scenarios

In [15]:
aggregate_metric('sync_lat_mean_ms').rename(columns={"b2_t1": "gp2x1","b2_t2": "gp2x2","b2_t3": "gp3x1","b2_t4": "gp3x2"})\
    .style.applymap(_df_style_high, subset=["gp2x1", "gp2x2", "gp3x1", "gp3x2"], value_yellow=2.0, value_red=5.0)

____
**FIO sync lattency Mean in ms (sync_lat_max_ms)**

- Total of FIO consecutive tests: 50
- Max IOPS on this job: 2k IOPS
- Max IOPS on gp2: 386 (128GiB)
- Max IOPS on gp3: 3000 [default] (128GiB) 

Summary of results:
- isolated gp2 become more reliable than single disk when burst balance ended

In [16]:
aggregate_metric('sync_lat_max_ms').rename(columns={"b2_t1": "gp2x1","b2_t2": "gp2x2","b2_t3": "gp3x1","b2_t4": "gp3x2"}).\
    style.applymap(_df_style_high, subset=["gp2x1", "gp2x2", "gp3x1", "gp3x2"], value_yellow=50.0, value_red=100.0)

____
**FIO sync lattency Standard Deviation in ms (sync_lat_max_ms)**

- Total of FIO consecutive tests: 50
- Max IOPS on this job: 2k IOPS
- Max IOPS on gp2: 386 (128GiB)
- Max IOPS on gp3: 3000 [default] (128GiB) 

Summary of results:
- gp2: similar/expected deviation when throttling for both disk layouts

In [17]:
aggregate_metric('sync_lat_stddev_ms').rename(columns={"b2_t1": "gp2x1","b2_t2": "gp2x2","b2_t3": "gp3x1","b2_t4": "gp3x2"}).\
    style.applymap(_df_style_high, subset=["gp2x1", "gp2x2", "gp3x1", "gp3x2"], value_red=1.0)

____
**FIO sync lattency - all metrics by node - in ms (sync_lat_max_ms)**

- Total of FIO consecutive tests: 50
- Max IOPS on this job: 2k IOPS
- Max IOPS on gp2: 386 (128GiB)
- Max IOPS on gp3: 3000 [default] (128GiB) 

Summary of results: []

In [18]:
node_metrics = aggregate_by_node()
for node in list(node_metrics.keys()):
    print(f"#> {node} [{node_metrics[node][0]['battery_id']}]")
    display(pd.read_json(json.dumps(node_metrics[node])))

#> ip-10-0-137-218.ec2.internal [b2_t1]

,battery_id,job_Id,sync_lat_max_ms,sync_lat_mean_ms,sync_lat_stddev_ms,sync_lat_p99_ms,sync_lat_p99.9_ms
0,b2_t1,a1,21.362522,0.789064,0.430956,1.925120,4.751360
1,b2_t1,a2,70.671594,1.056788,0.582749,2.277376,6.782976
2,b2_t1,a3,14.560474,1.070381,0.529805,2.244608,6.586368
3,b2_t1,a4,23.222146,1.068620,0.537326,2.375680,6.324224
4,b2_t1,a5,76.327184,1.069686,0.586911,2.342912,6.520832
5,b2_t1,b1,16.081376,1.075730,0.545497,2.375680,6.782976
6,b2_t1,b2,78.391998,1.065582,0.615213,2.375680,6.455296
7,b2_t1,b3,87.659569,1.041871,0.599280,2.211840,6.586368
8,b2_t1,b4,75.570967,1.060716,0.621720,2.244608,6.651904
9,b2_t1,b5,90.578402,1.053578,0.612393,2.342912,6.651904
10,b2_t1,c1,73.352157,1.070039,0.620716,2.342912,6.848512
11,b2_t1,c2,85.045124,1.160528,0.663657,2.637824,7.438336
12,b2_t1,c3,12.304493,1.193205,0.602402,2.801664,6.914048
13,b2_t1,c4,14.302122,1.106304,0.562018,2.441216,7.110656
14,b2_t1,c5,87.205052,1.114071,0.633961,2.441216,7.045120
15,b2_t1,d1,83.430267,1.094274,0.616942,2.375680,7.110656
16,b2_t1,d2,19.871437,1.085720,0.549715,2.310144,6.914048
17,b2_t1,d3,13.603607,1.073432,0.538930,2.310144,6.717440
18,b2_t1,d4,14.650788,1.107403,0.554933,2.441216,6.717440
19,b2_t1,d5,40.155084,1.132898,0.598044,2.572288,6.979584
20,b2_t1,e1,74.314233,1.161496,0.646730,2.637824,7.372800
21,b2_t1,e2,16.248647,1.196111,0.624049,2.834432,7.634944
22,b2_t1,e3,84.335387,1.110110,0.626943,2.441216,6.782976
23,b2_t1,e4,83.818774,1.082656,0.606692,2.441216,6.455296
24,b2_t1,e5,18.223823,1.081432,0.556802,2.342912,7.045120
25,b2_t1,f1,18.969413,1.073290,0.541922,2.342912,6.586368
26,b2_t1,f2,78.021850,1.101784,0.620040,2.441216,6.586368
27,b2_t1,f3,16.521411,1.126240,0.568856,2.506752,6.717440
28,b2_t1,f4,56.012427,1.113870,0.589814,2.473984,6.717440
29,b2_t1,f5,17.123146,1.086203,0.551999,2.310144,6.848512
30,b2_t1,g1,19.361459,1.157267,0.589222,2.605056,6.651904
31,b2_t1,g2,83.561105,1.158294,0.650944,2.670592,6.979584
32,b2_t1,g3,98.943857,4.443336,3.825136,17.956864,28.704768
33,b2_t1,g4,127.694486,5.903099,3.863416,18.481152,33.816576
34,b2_t1,g5,104.226220,5.923943,3.925166,20.578304,36.438016
35,b2_t1,h1,130.507872,5.924606,3.906435,20.054016,36.438016
36,b2_t1,h2,98.664309,5.917048,3.876710,18.481152,39.059456
37,b2_t1,h3,137.669736,5.899914,3.816676,18.219008,36.438016
38,b2_t1,h4,101.321112,5.904183,3.804448,18.219008,36.438016
39,b2_t1,h5,104.007671,5.896509,3.839013,18.219008,36.438016
40,b2_t1,i1,127.577284,5.905301,3.836431,18.481152,36.438016
41,b2_t1,i2,106.278686,5.933013,3.845477,18.481152,36.438016
42,b2_t1,i3,101.747360,5.918613,3.819285,18.481152,36.438016
43,b2_t1,i4,130.361933,5.917122,3.912056,18.481152,36.438016
44,b2_t1,i5,125.034424,5.912760,3.892198,18.219008,36.438016
45,b2_t1,j1,109.374159,5.926906,3.862755,18.481152,36.438016
46,b2_t1,j2,130.202472,5.928445,3.870202,18.481152,39.059456
47,b2_t1,j3,106.458561,5.936170,3.899451,19.005440,39.059456
48,b2_t1,j4,162.079734,5.940704,3.918237,18.481152,36.438016
49,b2_t1,j5,130.081632,5.938387,3.965393,18.481152,39.059456

#> ip-10-0-142-88.ec2.internal [b2_t2]

,battery_id,job_Id,sync_lat_max_ms,sync_lat_mean_ms,sync_lat_stddev_ms,sync_lat_p99_ms,sync_lat_p99.9_ms
0,b2_t2,a1,42.921417,1.319287,0.703880,2.703360,9.502720
1,b2_t2,a2,28.750373,1.348980,0.723067,2.932736,9.764864
2,b2_t2,a3,19.301707,1.334769,0.688169,2.899968,9.240576
3,b2_t2,a4,35.648584,1.322543,0.707594,2.736128,9.764864
4,b2_t2,a5,80.075922,1.363166,0.754138,2.998272,9.895936
5,b2_t2,b1,16.037055,1.342571,0.687214,2.801664,9.371648
6,b2_t2,b2,67.246422,1.380487,0.751622,2.965504,9.764864
7,b2_t2,b3,68.943773,1.349172,0.730728,2.899968,8.978432
8,b2_t2,b4,17.130309,1.323254,0.679319,2.834432,9.109504
9,b2_t2,b5,83.009037,1.314879,0.751204,2.768896,10.027008
10,b2_t2,c1,21.638637,1.288025,0.674037,2.637824,9.371648
11,b2_t2,c2,16.988951,1.310626,0.682124,2.768896,9.240576
12,b2_t2,c3,19.812239,1.325149,0.687454,2.768896,9.502720
13,b2_t2,c4,18.536172,1.327079,0.701443,2.899968,9.502720
14,b2_t2,c5,20.644870,1.326199,0.704009,2.834432,10.027008
15,b2_t2,d1,57.498424,1.343508,0.744269,2.965504,10.158080
16,b2_t2,d2,24.036400,1.340880,0.694338,2.834432,9.502720
17,b2_t2,d3,82.225018,1.341512,0.750067,2.867200,9.633792
18,b2_t2,d4,80.986273,1.338761,0.753507,2.899968,10.027008
19,b2_t2,d5,22.170003,1.338119,0.704970,2.867200,9.895936
20,b2_t2,e1,18.404405,1.313773,0.680368,2.736128,9.633792
21,b2_t2,e2,79.907495,1.337504,0.742640,2.834432,9.633792
22,b2_t2,e3,23.808354,1.352634,0.714605,2.932736,9.764864
23,b2_t2,e4,24.078522,1.321663,0.686635,2.768896,9.633792
24,b2_t2,e5,25.349922,1.355056,0.709999,2.867200,9.895936
25,b2_t2,f1,18.479378,1.292314,0.670444,2.605056,9.502720
26,b2_t2,f2,16.161620,1.270952,0.638763,2.506752,8.454144
27,b2_t2,f3,78.555610,1.304639,0.730971,2.768896,9.633792
28,b2_t2,f4,72.935047,1.320057,0.787872,2.899968,10.813440
29,b2_t2,f5,18.523360,1.304557,0.661377,2.736128,8.716288
30,b2_t2,g1,76.735155,1.302631,0.725293,2.736128,9.502720
31,b2_t2,g2,78.265215,1.318653,0.734398,2.670592,9.764864
32,b2_t2,g3,18.506985,1.278411,0.660164,2.605056,9.109504
33,b2_t2,g4,24.294061,1.326244,0.693937,2.801664,9.633792
34,b2_t2,g5,79.426097,1.340073,0.750579,2.867200,10.027008
35,b2_t2,h1,79.757899,1.319705,0.741914,2.736128,9.764864
36,b2_t2,h2,37.476716,1.336998,0.725465,2.899968,10.158080
37,b2_t2,h3,79.369348,5.690261,3.389939,18.219008,25.821184
38,b2_t2,h4,88.399460,5.808433,3.408925,18.219008,25.821184
39,b2_t2,h5,57.270093,5.841664,3.453397,18.219008,25.821184
40,b2_t2,i1,91.292011,5.849903,3.465687,18.219008,23.724032
41,b2_t2,i2,70.225794,5.862731,3.476876,18.219008,24.248320
42,b2_t2,i3,62.654754,5.841414,3.440871,18.219008,25.559040
43,b2_t2,i4,75.292917,5.845320,3.462567,18.219008,25.296896
44,b2_t2,i5,78.167728,5.839628,3.483655,18.219008,26.083328
45,b2_t2,j1,79.784803,5.854145,3.480325,18.219008,26.083328
46,b2_t2,j2,65.524540,5.847236,3.483793,18.219008,25.821184
47,b2_t2,j3,78.996063,5.845602,3.453708,18.219008,23.724032
48,b2_t2,j4,62.459498,5.839305,3.418863,18.219008,23.986176
49,b2_t2,j5,65.139597,5.827451,3.427648,18.219008,25.821184

#> ip-10-0-137-24.ec2.internal [b2_t3]

,battery_id,job_Id,sync_lat_max_ms,sync_lat_mean_ms,sync_lat_stddev_ms,sync_lat_p99_ms,sync_lat_p99.9_ms
0,b2_t3,a1,68.017842,1.333167,0.772607,3.653632,8.454144
1,b2_t3,a2,18.266890,1.687630,0.841022,4.227072,9.502720
2,b2_t3,a3,78.664201,1.650445,0.836908,3.883008,8.978432
3,b2_t3,a4,33.433859,1.641819,0.819819,4.145152,9.240576
4,b2_t3,a5,76.929612,1.666814,0.871086,4.079616,9.764864
5,b2_t3,b1,66.840544,1.681684,0.853895,4.046848,9.371648
6,b2_t3,b2,46.956900,1.774595,0.952194,5.079040,10.551296
7,b2_t3,b3,22.667406,1.744623,0.914686,4.751360,10.027008
8,b2_t3,b4,33.258572,1.722502,0.917649,4.489216,10.420224
9,b2_t3,b5,32.785594,1.681496,0.844867,4.177920,9.633792
10,b2_t3,c1,59.235491,1.601921,0.844636,3.883008,9.895936
11,b2_t3,c2,79.425341,1.593500,0.803912,3.457024,8.716288
12,b2_t3,c3,24.650658,1.629773,0.790597,3.653632,8.847360
13,b2_t3,c4,16.888352,1.612760,0.762405,3.457024,8.847360
14,b2_t3,c5,23.930174,1.596592,0.786703,3.751936,9.109504
15,b2_t3,d1,19.653545,1.645699,0.843539,4.227072,10.027008
16,b2_t3,d2,21.477089,1.615442,0.787897,3.620864,9.240576
17,b2_t3,d3,78.386342,1.609966,0.823499,3.588096,9.240576
18,b2_t3,d4,83.007022,1.595604,0.861799,3.555328,9.240576
19,b2_t3,d5,25.149553,1.597500,0.775678,3.489792,9.109504
20,b2_t3,e1,22.188355,1.581205,0.756247,3.325952,8.978432
21,b2_t3,e2,79.116955,1.620661,0.808597,3.489792,8.716288
22,b2_t3,e3,30.646049,1.635464,0.768980,3.588096,8.716288
23,b2_t3,e4,18.313882,1.622308,0.767243,3.555328,8.847360
24,b2_t3,e5,18.892629,1.667598,0.809127,3.948544,8.978432
25,b2_t3,f1,21.439933,1.704640,0.866086,4.554752,9.764864
26,b2_t3,f2,19.664112,1.675780,0.824882,4.046848,9.240576
27,b2_t3,f3,79.879006,1.627094,0.854483,4.112384,9.240576
28,b2_t3,f4,42.729975,1.640222,0.799137,3.653632,9.109504
29,b2_t3,f5,83.259088,1.666991,0.898885,4.112384,9.764864
30,b2_t3,g1,42.321099,1.657269,0.883888,4.423680,9.895936
31,b2_t3,g2,81.137182,1.649059,0.877024,4.145152,9.502720
32,b2_t3,g3,33.762865,1.687637,0.854193,4.292608,9.502720
33,b2_t3,g4,20.463802,1.659621,0.824036,4.227072,8.978432
34,b2_t3,g5,21.846251,1.659012,0.829251,4.112384,9.240576
35,b2_t3,h1,26.704316,1.681932,0.890803,4.227072,10.420224
36,b2_t3,h2,26.717716,1.615984,0.805530,3.719168,9.371648
37,b2_t3,h3,23.694303,1.646508,0.813346,3.883008,9.240576
38,b2_t3,h4,77.473870,1.623840,0.825446,3.751936,8.978432
39,b2_t3,h5,79.897140,1.632903,0.856980,3.948544,9.109504
40,b2_t3,i1,80.932569,1.675081,0.917261,4.046848,9.633792
41,b2_t3,i2,76.433845,1.710924,0.862999,4.112384,9.109504
42,b2_t3,i3,78.075309,1.746246,0.949621,4.685824,10.158080
43,b2_t3,i4,82.724512,1.773936,0.988854,4.751360,10.289152
44,b2_t3,i5,80.088464,1.690446,0.889230,4.079616,9.633792
45,b2_t3,j1,77.763431,1.620321,0.794586,3.391488,8.716288
46,b2_t3,j2,79.562965,1.713289,0.910338,4.423680,10.027008
47,b2_t3,j3,80.719352,1.796371,1.010509,4.947968,10.551296
48,b2_t3,j4,24.492515,1.628370,0.820270,3.784704,9.371648
49,b2_t3,j5,20.263875,1.614145,0.783822,3.751936,8.847360

#> ip-10-0-133-152.ec2.internal [b2_t4]

,battery_id,job_Id,sync_lat_max_ms,sync_lat_mean_ms,sync_lat_stddev_ms,sync_lat_p99_ms,sync_lat_p99.9_ms
0,b2_t4,a1,82.157969,1.712503,0.959877,4.685824,11.075584
1,b2_t4,a2,84.258343,1.756673,1.073758,5.144576,13.172736
2,b2_t4,a3,82.106066,1.626919,0.860998,3.915776,10.158080
3,b2_t4,a4,34.026425,1.633420,0.842392,3.915776,10.420224
4,b2_t4,a5,64.642143,1.701093,0.917508,4.423680,10.551296
5,b2_t4,b1,27.682156,1.759722,0.985698,5.079040,11.730944
6,b2_t4,b2,86.332541,1.649717,0.877783,3.784704,10.682368
7,b2_t4,b3,19.102149,1.654040,0.821403,3.817472,10.420224
8,b2_t4,b4,18.097099,1.703117,0.850724,3.948544,10.682368
9,b2_t4,b5,82.894287,1.630997,0.880190,3.620864,10.813440
10,b2_t4,c1,34.250775,1.688473,0.907226,4.358144,11.730944
11,b2_t4,c2,50.890176,1.540552,0.757315,3.096576,10.158080
12,b2_t4,c3,81.638564,1.653208,0.865012,3.883008,10.027008
13,b2_t4,c4,34.058662,1.679135,0.840935,4.046848,10.027008
14,b2_t4,c5,35.630164,1.620467,0.794594,3.555328,10.158080
15,b2_t4,d1,59.792853,1.627862,0.838632,3.620864,10.551296
16,b2_t4,d2,22.930208,1.601489,0.768104,3.391488,9.633792
17,b2_t4,d3,18.953083,1.682410,0.846683,3.883008,10.551296
18,b2_t4,d4,35.577028,1.690741,0.880741,4.112384,11.075584
19,b2_t4,d5,82.663219,1.613168,0.859680,3.719168,10.944512
20,b2_t4,e1,84.178326,1.616357,0.827707,3.489792,10.158080
21,b2_t4,e2,84.137220,1.585113,0.826806,3.391488,10.420224
22,b2_t4,e3,65.512945,1.600341,0.796826,3.391488,10.158080
23,b2_t4,e4,42.574045,1.694389,0.903739,4.423680,11.075584
24,b2_t4,e5,54.098514,1.656733,0.841158,3.751936,10.289152
25,b2_t4,f1,80.975664,1.721286,1.012981,4.620288,12.517376
26,b2_t4,f2,82.165180,1.736041,0.998473,4.816896,11.337728
27,b2_t4,f3,38.448971,1.645838,0.830153,3.653632,10.420224
28,b2_t4,f4,20.558225,1.663913,0.839331,3.850240,10.682368
29,b2_t4,f5,17.461157,1.641694,0.815392,3.620864,10.944512
30,b2_t4,g1,22.709828,1.636465,0.814237,3.620864,10.420224
31,b2_t4,g2,73.773492,1.599612,0.820261,3.424256,10.027008
32,b2_t4,g3,71.800190,1.619913,0.814386,3.522560,10.158080
33,b2_t4,g4,20.252410,1.573605,0.779804,3.522560,10.027008
34,b2_t4,g5,84.670361,1.642198,0.888350,3.784704,10.289152
35,b2_t4,h1,82.534891,1.669151,0.915968,3.883008,10.944512
36,b2_t4,h2,69.176836,1.716879,0.905877,4.227072,10.944512
37,b2_t4,h3,83.234735,1.724542,0.969917,4.554752,11.599872
38,b2_t4,h4,35.095336,1.746813,0.937789,4.489216,11.206656
39,b2_t4,h5,22.740948,1.668419,0.838676,3.948544,10.289152
40,b2_t4,i1,19.667939,1.727930,0.893797,4.423680,10.682368
41,b2_t4,i2,82.139685,1.690698,0.945605,4.292608,11.337728
42,b2_t4,i3,84.682646,1.678174,0.936211,4.014080,11.862016
43,b2_t4,i4,19.903843,1.637586,0.820174,3.784704,10.682368
44,b2_t4,i5,68.709482,1.681608,0.891130,3.817472,10.813440
45,b2_t4,j1,82.784139,1.657394,0.906569,3.719168,10.551296
46,b2_t4,j2,76.739871,1.614540,0.831806,3.457024,10.289152
47,b2_t4,j3,21.593767,1.728508,0.897712,4.292608,10.813440
48,b2_t4,j4,86.788914,1.668683,0.936373,4.177920,10.944512
49,b2_t4,j5,19.679278,1.615724,0.792559,3.489792,10.289152